### PR TITLE
Added Unbind tests

### PR DESCRIPTION
**Pull request by mschultz4**
In response to issue #166, I added a couple of more tests for `Unbind`.  Please let me know if you see potential improvements.

### CODE REVIEW

**Comment by LeaVerou** [comment]
Thanks so much!!
We don't yet implement multiple namespaces though, so those tests should fail. Wanna comment them out until we do?

**Comment by mschultz4** [comment]
Certainly.  Which tests should I comment out exactly?  I am not sure I understand which will fail.  Thanks

**Comment by LeaVerou** [comment]
Just convert events that use namespaces like `click.namespace1.foo` to use one namespace, e.g. either `click.namespace1` or `click.foo`. 
However, did these pass when you run them? If so, there must be some bug in them, since the functionality they're testing is not supported!

**Comment by mschultz4** [comment]
Oh ok, I see.  That test was actually written by @jxc876 within request #169 and merged already.  The reason the test is passing is because the listeners are attached to the first namespace and not the second level.  I am not sure why the second namespace was originally included, but it adds nothing to the test and is obviously confusing so I removed it. 

When I attach the listeners to the second namespace and run the test, they do indeed fail as expected.

**Comment by LeaVerou** [comment]
Cool! Please make these changes to this PR and it's good to go!

**Comment by mschultz4** [comment]
Awesome!  I already included the changes in my [commit](https://github.com/mschultz4/bliss/commit/45dd8ba9ebe5ee0681f02a185c76b6ad5ecfba9d).

**Comment by LeaVerou** [comment]
Oh, I hadn't noticed. Merged now, thanks!!

**Pull request merged**
