### PR TITLE
Removed trailing whitespace

### PR DESCRIPTION
**Pull request by softwarespot**
According to .editorconfig trailing whitespace should be trimmed. So I took the liberty of doing it manually.

### CODE REVIEW

**Comment by LeaVerou** [comment]
This branch has conflicts :( please pull & merge?
Thanks!!

**Comment by dperrymorrow** [comment]
to rebase ```LeaVerou/Bliss``` onto your branch 
```
$ git remote add upstream git@github.com:LeaVerou/bliss.git
$ git fetch upstream 
$ git rebase upstream/gh-pages
```
you can either rebase or merge, but merge will create a merge commit.
your local code will not have the latest from the main repository.

**Comment by LeaVerou** [comment]
In general btw, I don't see the point of individual PRs for whitespace removal. 
I’m fine with PRs that do that AND one more thing, as we can always add `w=1` to the URL to ignore the whitespace changes.

**Comment by softwarespot** [comment]
@dperrymorrow, thanks for that. I had the latest changes when I committed this, so it's weird these conflicts existed.

@LeaVerou, I respect that and thus will revoke this PR, with hope of committing something in the near future.

**Comment by LeaVerou** [comment]
Sorry, I didn’t mean to discourage you! Sending a PR for whitespace removal is fine, and **will** be merged.
What I meant was, even though generally it's encouraged that PRs are separate for separate things, sending a PR for whitespace removal AND something else would be ok.

**Pull request closed without merging**
