### PR TITLE
Add test for $.ready()

### PR DESCRIPTION
**Pull request by wcastand**

### CODE REVIEW

**Comment by dperrymorrow** [comment]
@wcastand 

can you fix the indentation after your describe block?

It looks like the tests so far just test the triggering of the Promise returned by the ```$.ready``` event.
Under the covers it looks like ready is triggered by ```DOMContentLoaded``` event. 

```javascript
context.addEventListener("DOMContentLoaded", function(){
  resolve();
});
```

it would be great to have additional tests to ensure that the ```DOMContentLoaded``` event does indeed trigger the Bliss ```ready``` method to resolve the promise. 

Also you could test the other usage of ready to handle a retuned Promise.

```javascript
var promise = $.ready([context])
```

No need to close this pull request though, just keep pushing to your branch and this will update.
Thanks!

**Comment by LeaVerou** [comment]
> Under the covers it looks like ready is triggered by DOMContentLoaded event.

If `DOMContentLoaded` has already fired though, it will return a resolved promise. That's the difference of `$.ready` vs just using `addEventListener("DOMContentLoaded")`

**Comment by dperrymorrow** [comment]
Right... It would need ```context.readyState``` stubbed in the test to "loading" in order to capture the ```DOMContentLoaded``` event which would already have passed.

Ill post an example of how to stub that tomorrow. Also @wcastand if you want to just do the other two mentioned items, ill merge and I can tinker with that one.

**Comment by wcastand** [comment]
Hi,
That's weird, in my editor (sublime text), the indentation looks good but not once i pushed the file.
I have to admit, i'm a bit lost right now. I just made this test and it feels to simple.
But i have no clue how to test this.
If that's ok i will let you handle this one, and look how you do it, so i can learn.
(maybe you can fix the indentation issue too because on my computer the indentation is okay)

**Comment by dperrymorrow** [comment]
sure thing, merged.

**Comment by dperrymorrow** [comment]
and BTW I wasn't saying anything was wrong with the test  you wrote. Its great, thank you. I was just suggesting some other ways to test this method as well, **(and was having trouble explaining myself...)**

I should shut up on this repo and just keep writing tests :)

**Comment by wcastand** [comment]
ahah, don't worry. I completely agree with you, the test is not complete but i didn't know how to make it better.

**Comment by dperrymorrow** [comment]
@wcastand I added a few more to your spec file
https://github.com/LeaVerou/bliss/commit/6757db66f21bf78cc0ba6f417cdbca1db5b0bc99

I ended up mocking the ```document ``` as an element so i could control the readyState and when the event was dispatched. 

If you have any ideas of how to make this better the suite better, obviously go for it.

**Pull request merged**
