### PR TITLE
Initial commit for #130 ($.fetch test)

### PR DESCRIPTION
**Pull request by StrongRef**
Test template for `$.fetch`.

I also made a minor change to the implementation of `$.fetch`

sinon seems to require that `xhr.open` gets the url as a string, not an URL.
MDN says string as well:
`void open(DOMString method, DOMString url, optional boolean async, optional DOMString? user, optional DOMString? password);`

### CODE REVIEW

**Comment by zdfs** [comment]
@StrongRef - Can you do a pull and update your PR? We had a breaking build, but that's since been fixed.

**Comment by LeaVerou** [comment]
Also, changes to `bliss.js` will be overwritten once gulp runs, as it's a generated file.

**Comment by StrongRef** [comment]
@LeaVerou I made changes to bliss.shy.js and ran gulp.
Or did I miss anything?

**Comment by LeaVerou** [comment]
No, I did, sorry! Ignore my comment! :)

**Comment by StrongRef** [comment]
Wow, I should upgrade my git skills...
Anyway, I provided some tests for the basic functionality.

**Comment by dperrymorrow** [comment]
>Also, changes to bliss.js will be overwritten once gulp runs, as it's a generated file.

ok i feel really stupid now i did not know that. I think thats one more strong argument for a src and dist folder structure.

**Pull request closed without merging**
