### PR TITLE
tests for $.all

### PR DESCRIPTION
**Pull request by dperrymorrow**
Issue: #46 
- added sinon for spies
- changed the way classtype was being detected for expr

```Window``` is undefined in the test runner. so I changed to 
```javascript
expr.constructor.name
```
vs
```
instanceof
```

### CODE REVIEW

**Comment by zdfs** [comment]
Going to let @LeaVerou look at this since it touches core code.

**Comment by zdfs** [comment]
Also, this PR will put us up over 30 unit tests. Thanks everyone!

**Comment by dperrymorrow** [comment]
cool, open to suggestions as to how to have the test environment not puke on ```Window```
Looks like ```constructor.name``` is well supported so I went with that.
https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Object/constructor

**Comment by zdfs** [comment]
Regarding [this comment](https://github.com/LeaVerou/bliss/issues/47#issuecomment-163040176), I think @dperrymorrow is going to back out his changes to the core, leaving only a test.

**Comment by dperrymorrow** [comment]
yup, just tried it, passes against Chrome without messing with ```bliss.js``` will push change here in a second.

**Pull request merged**
