### PR TITLE
Added note for developers

### PR DESCRIPTION
**Pull request by franciscop**
I am interested in contributing to the project, so first I need to understand the source code. However the few comments in the code itself didn't help much, so when viewing the *docs* to see if there was something useful I found an overview of the library code which really helped me. It might also help other future contributors.

### CODE REVIEW

**Comment by LeaVerou** [comment]
Thanks, though not sure about this. I think it should be in CONTRIBUTING.md instead. What do others think?

**Comment by dperrymorrow** [comment]
thanks for contributing to Bliss,
IMO a link to the website in the minified file might be helpful for developers using bliss.

It would need to be done via gulp as it ulgifies https://github.com/LeaVerou/bliss/blob/gh-pages/gulpfile.js#L14 the source into the min files, so any comments will be ripped out.

**Comment by franciscop** [comment]
Is it okay if I add other comments to the source as I am reading and trying to understand it or it's better that I leave it as-is? I understand that it might be overkill for the original developers, but it might help new developers to understand the code. [I tend to err in the over-comment side](https://github.com/umbrellajs/umbrella/blob/master/src/umbrella.js) but of course I wouldn't take it as far.

**Comment by dperrymorrow** [comment]
hmm I'm not sure, @LeaVerou seems to feel that this information should go in a CONTRIBUTING.md file, so ill defer to her. I do feel that a link to the doc site would be helpful as a header in the min files.

**Comment by LeaVerou** [comment]
The link to the Bliss site should be included in the header, but I don't think specific links to the doc site should be there.
Also, while I can be guilty of undercommenting, I think overcommenting is just as harmful. Pointless obvious comments like:

```js
// Store the node as an array
parameter = [parameter];
```

add so much bloat and only help people too inexperienced with JS to even know its syntax, which need more experience to become good contributors anyway. For anyone else, they just add bloat and mask the actually meaningful comments. While JS libraries are good learning tools, their primary purpose is not to be code tutorials for basic language constructs. 

I really stand by what Jeff Atwood has written [here](http://blog.codinghorror.com/coding-without-comments/). QFE:

> While comments are neither inherently good or bad, they are frequently used as a crutch. You should always write your code as if comments didn't exist. This forces you to write your code in the simplest, plainest, most self-documenting way you can humanly come up with.

> As Sammy Larbi said in Common Excuses Used To Comment Code, if your feel your code is too complex to understand without comments, your code is probably just bad. Rewrite it until it doesn't need comments any more. If, at the end of that effort, you still feel comments are necessary, then by all means, add comments. Carefully.

**Comment by franciscop** [comment]
Yes, that's completely true, I regret it now and I'm deleting many useless since I started that project when I was starting to learn javascript and now try to follow that same guideliness. Okay, thanks for the clarification, I'll close this then :smile:

**Pull request closed without merging**
