### PR TITLE
Jshint

### PR DESCRIPTION
**Pull request by dperrymorrow**
added jshint to karma preprocessors.

I have the settings set pretty loose per #37 conversation.
In this pull i have also added some missing semicolons that were caught with the lint.

In the future they can be adjusted stricter / looser 

```javascript
jshint: {
  options: {
    curly: true,
    eqeqeq: false,
    loopfunc: true,
    immed: true,
    latedef: true,
    newcap: true,
    noarg: true,
    expr: true,
    sub: true,
    undef: false,
    boss: true,
    devel: true,
    eqnull: true,
    browser: true
  },
  summary: false
}
```

### CODE REVIEW

**Comment by zdfs** [comment]
Since we've talked about this already, I'm going to merge it and see how we get along. We can always back it out.

**Comment by dperrymorrow** [comment]
Thanks, I find it useful even if its as loose as its currently set. 
Found some missing semicolons in my tests :) 

I think it may have more benefit later on with many more folks committing to enforce style to 
@LeaVerou 's

**Comment by LeaVerou** [comment]
Thanks @dperrymorrow! Any chance somebody could add comments next to the settings so we know what they do?
(I can guess by the names for some, but generally they’re pretty cryptic)

**Comment by dperrymorrow** [comment]
http://jshint.com/docs/options/ is the full list. 
I can add comments to the ones we have in our prefs

**Comment by zdfs** [comment]
Thanks @dperrymorrow.

**Comment by dperrymorrow** [comment]
I have commented the JsHint options per request. 
https://github.com/LeaVerou/bliss/blob/gh-pages/karma.conf.js#L38

**Pull request merged**
