### PR TITLE
Fix JSHint Warnings / Errors and remove two "bad" test cases in FetchSpec.

### PR DESCRIPTION
**Pull request by StrongRef**

### CODE REVIEW

**Comment by LeaVerou** [comment]
Hi there,

Thanks for contributing!
In the future, please try to separate different things into different PRs.

I do not agree with the code style changes. Point taken though, I should replace .hshintrc with an .eslintrc.json, I haven't used JSHint in a while which explains why it's config is out of date.

Why remove the testcases? What's wrong with them?

**Comment by StrongRef** [comment]
Those tests are failing when using Sinon 1.17.4.
And it is probably correct as well, should a 404 be treated as an error?

I agree that this could be multiple PRs but they do fix warnings / errors for `gulp` and `npm test` that is why I went with a single PR.

**Comment by LeaVerou** [comment]
Yes. I will add the eslint config file and update the sinon version asap.

**Comment by LeaVerou** [comment]
Done

**Comment by StrongRef** [comment]
- `"sinon": "^1.17.3"` => `"sinon": "1.17.3"` version `1.17.4` is broken.
- Remove JSHint preprocessor from karma.conf.js.

**Comment by LeaVerou** [comment]
> We should probably use ESLint from karma? Let me know if you want me to look into this one.

Yes! If you know how to do it, any PRs would be appreciated! Otherwise I can look into it!

**Pull request closed without merging**
