### PR TITLE
#35 Remove Chrome from karma.config

### PR DESCRIPTION
**Pull request by zdfs**
This if for #35. Can be rejected, but I don’t think we need to call
Chrome by default for the build. Developers can add it to their
environment at any time.

### CODE REVIEW

**Comment by zdfs** [comment]
WE ARE GREEN, PEOPLE.

**Comment by LeaVerou** [comment]
I’m fine with removing it, but I’d like to check with @dperrymorrow first, since he put it in.

**Comment by zdfs** [comment]
Anyone have an idea why the build skips a test? Same thing happens when running `npm test`.

**Comment by zdfs** [comment]
@dperrymorrow signed off here: https://github.com/LeaVerou/bliss/issues/35

**Comment by LeaVerou** [comment]
Yeah, I just saw! Also, yay for being green, finally! Wheee!
What is `.idea`? It’s added in the gitignore…

**Comment by zdfs** [comment]
Sorry. It was for my webstorm IDE. We can remove it, if you'd like. I switched to atom.

**Comment by LeaVerou** [comment]
Yeah, that looks like something that should be in your global gitignore :)

**Comment by zdfs** [comment]
Noted. I'll update.

**Comment by zdfs** [comment]
All done.

**Comment by zdfs** [comment]
I found why it was only running 15 of the 16 tests. Not my code, so I'll leave it as is. There an `xit` in `setSpec.js`.

**Pull request merged**
