### PR TITLE
Tests for $.fetch #130

### PR DESCRIPTION
**Pull request by StrongRef**

### CODE REVIEW

**Comment by dperrymorrow** [comment]
hey it looks like you have some conflicts 
you'll need to fetch upstream and rebase it onto your branch. 

```
$ git remote add upstream git@github.com:LeaVerou/bliss.git
$ git fetch upstream 
$ git rebase upstream/gh-pages
```

thanks for working  on these.

**Comment by StrongRef** [comment]
I'm sorry about the delay.
Trying to work my way around fancy-pants-git! :+)

**Comment by dperrymorrow** [comment]
no worries, if you have conflicts to resolve, its helpful to have a mergetool. 
http://stackoverflow.com/questions/7227826/whats-a-good-free-visual-merge-tool-for-git-on-windows

im assuming you are on windows?

**Comment by StrongRef** [comment]
Oh, that's no problem.
I'm just trying to get familiar with the PR-Fix-PR workflow!

**Comment by dperrymorrow** [comment]
great, thanks for fixing up the conficts

**Pull request merged**
