### PR TITLE
Fix Travis build (#192)

### PR DESCRIPTION
**Pull request by StrongRef**
- Remove Firefox launcher.
- Remove gitter notifications (is this still used?).
- Use Ubuntu trusty instead of precise.
- Update chrome-launcher.
- Update node version.

### CODE REVIEW

**Comment by LeaVerou** [comment]
Thanks!

Aw, so the Firefox launcher was causing this?

PR has conflicts, can you rebase please?

**Comment by StrongRef** [comment]
No problem!

No, Firefox is not used at the moment. We could perhaps include Firefox in the karma configuration (and configure travis).
Should I have a look?

The issue was that some of the required dependencies for Chrome were too old when using Ubuntu 12.04. We are now using Ubuntu 14.04 (beta feature of Travis CI) that solves this issue.

I will fix PR during the day.

**Comment by LeaVerou** [comment]
Sorry this was kind of forgotten! Should I merge this?

**Comment by StrongRef** [comment]
Yep, it seems to work!

**Comment by LeaVerou** [comment]
Merged then, thanks!

**Pull request merged**
