### PR TITLE
Ensure $.create creates a div when there are no arguments

### PR DESCRIPTION
**Pull request by guoguo12**
Now passes the "creates a div when there are no arguments" test in `CreateSpec.js`.

### CODE REVIEW

**Comment by guoguo12** [comment]
Great project, by the way!

**Comment by kurtextrem** [comment]
I do think the whole method can be rewritten without mentioning "arguments" once (https://github.com/petkaantonov/bluebird/wiki/Optimization-killers#3-managing-arguments)
as undefined results in false via `!tag`.

**Comment by guoguo12** [comment]
You're totally right. So something like this?

```javascript
	create: function (tag, o) {
		if (tag === void 0) {
			return document.createElement("div");
		}

		if (o === void 0) {
```

It does seems a little less readable though.

**Comment by kurtextrem** [comment]
I'd do it like that:
`if (!tag && !o) // no args
      return ....

if (!o)` :)

**Comment by guoguo12** [comment]
Okay, thanks. How does it look now?

**Comment by kurtextrem** [comment]
Looks good to me. However, I'm not the creator of this repo, so it could be that Lea prefers some other code style :+1: 
(I've also seen that bliss sets `use strict` meaning that my link is not relevant - sorry for the trouble!)

**Comment by kimroen** [comment]
I'm slightly confused - Lea fixed this, and the test passed when I committed it. Fixed: 55667c614a070f5d24dc06f5bb41e7ee8e10be5a in response to #13

Are you seeing something else locally? Maybe it broke since then?

**Comment by guoguo12** [comment]
Interesting. As far as I can tell, after the commit you mentioned above, cb7fd3d added this line:

```js
delete o.tag;
```

which then broke the test. (When there are no arguments, `o` is undefined.)

Here's the test results I see:

```
Chrome 47.0.2526 (Windows 8.1 0.0.0) $.create creates a div when there are no arguments FAILED
        TypeError: Cannot convert undefined or null to object
            at Function.extend.create (C:/Users/guogu_000/Git/bliss/bliss.js:87:10)
            at Context.<anonymous> (C:/Users/guogu_000/Git/bliss/tests/DOM/CreateSpec.js:34:19)
PhantomJS 1.9.8 (Windows 8 0.0.0) $.create creates a div when there are no arguments FAILED
        TypeError: 'undefined' is not an object (evaluating 'delete o.tag')
            at C:/Users/guogu_000/Git/bliss/bliss.js:87
            at C:/Users/guogu_000/Git/bliss/tests/DOM/CreateSpec.js:34
Chrome 47.0.2526 (Windows 8.1 0.0.0): Executed 11 of 12 (1 FAILED) (skipped 1) (0.012 secs / 0.002 secs)
PhantomJS 1.9.8 (Windows 8 0.0.0): Executed 11 of 12 (1 FAILED) (skipped 1) (0.018 secs / 0.001 secs)
TOTAL: 2 FAILED, 20 SUCCESS
```

**Comment by kurtextrem** [comment]
I'd say @guoguo12's fix is the best solution here (also perf wise).

**Comment by kimroen** [comment]
That makes sense :)

**Comment by LeaVerou** [comment]
Sorry for breaking this! I just moved the delete in the conditional, which fixed it for all cases with zero extra code.
The only case it doesn't address is if you have BOTH a tag as an argument AND as an option to the object (in which case you get a tag attribute), but I don't think that’s something we should address.

**Comment by guoguo12** [comment]
Sounds good!

**Pull request closed without merging**
