### PR TITLE
fixing typo, assuring present before delete

### PR DESCRIPTION
**Pull request by dperrymorrow**
fixed typo in it function name, assuring that o.tag is
present before invoking delete on it.

there were some tests failing because o was undefined when trying to ```delete o.tag```
Also fixed a typo in the function name that was causing 2 assertions to not run.

### CODE REVIEW

**Comment by LeaVerou** [comment]
Thanks!!
I already fixed the delete issue earlier today, could you remove it from this PR so I can merge the other change? It shows merge conflicts now…
(in general, please try sending separate PRs for separate changes, for this very reason)

**Comment by dperrymorrow** [comment]
Ok fixed that up, and merged from upstream and tests now pass. 
Will only do one change per pull in the future.

**Comment by zdfs** [comment]
@LeaVerou - Anything else you want to add? Otherwise, I can merge.

**Comment by dperrymorrow** [comment]
all good on this tiny fix, thanks!

**Pull request merged**
