### PR TITLE
improvement on docs: suggestion about how to avoid errors when $ returns null

### PR DESCRIPTION
**Pull request by fcalderan**
Inserted some code to explain how to previously check if a node retrieved by ```$``` is null, and how to avoid to apply chained methods in this scenario. I think this could be a useful note and it encourages the adoption of a variable as cached reference

the suggested code:

```
// Check if the .foo element exists
// and set an attribute by using a variable "foo"
// as a reference of the element
var foo;
if (foo = $(".foo")) {
    foo.setAttribute("title", "yolo");
}
```

Note: as a side effect of this commit other lines are affected just because of the _autotrim_ function enabled on my ```Atom``` editor

### CODE REVIEW

**Comment by kurtextrem** [comment]
Is this good for codeflow?
I think imitating jQuery would be better here (neither throws an error, nor does anything)

**Comment by zdfs** [comment]
I'm going to let @LeaVerou make a call on this one.

**Comment by LeaVerou** [comment]
jQuery can do this because it doesn't use elements, everything is a collection.
How would we do this?
We could return an empty object (`{}`), which would prevent such errors, but then it would be inconsistent and hard to check for (how do you check if anything was returned?). Any ideas?
I do agree that it's kind of awkward as it stands…

**Comment by kurtextrem** [comment]
checking length or the "or" check? (return ... || {})

**Comment by LeaVerou** [comment]
No, I'm saying, if we return `{}` instead of null, it's harder for Bliss users to check if the element exists.
Also, that returning an object sometimes and an element sometimes is inconsistent.

**Comment by kurtextrem** [comment]
Oh, that is what you mean. Sorry. Well, we could return `{length:0}` to make it "checkable", but yeah not the best thing I guess.

**Comment by LeaVerou** [comment]
If we’re not going to change the `$` method, then we should probably merge this.
However, I'd rather avoid assignments in conditionals. I would change it so that the assignment is outside, and the conditional is just `if (foo)`

**Comment by fcalderan** [comment]
I'll provide the update in a few hours with a new PR

**Comment by LeaVerou** [comment]
Merged, thanks!

**Pull request merged**
